### ISSUE TITLE
Getting Error: spawn E2BIG

### ISSUE THREAD

**Issue by PrashantTapase** [TJkrusinski/NodePDF#51]
when i try for big data i am getting this error

```
internal/child_process.js:302
    throw errnoException(err, 'spawn');
    ^

Error: spawn E2BIG
    at exports._errnoException (util.js:953:11)
    at ChildProcess.spawn (internal/child_process.js:302:11)
    at exports.spawn (child_process.js:372:9)
    at Object.exports.execFile (child_process.js:139:15)
    at Object.exports.exec (child_process.js:99:18)
```

**Comment by mouryaamit** [comment]
+1
@PrashantTapase , Any solution you
